[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild" # Optional, but often recommended for faster builds
  environment = { NODE_VERSION = "18" } # Or a different supported version like "16" or "20"