[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-go"
    [plugins.inputs]
      functionsDir = "netlify/functions" # Ensure this matches

[build]
  publish = "dist"